name: provider_start
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  # Utilities
  flutter_launcher_icons: ^0.7.3
  shared_preferences: ^0.5.3+4
  app_settings: ^1.0.6+2
  device_info: ^0.4.0+3
  path_provider: ^1.2.0
  connectivity: ^0.4.4
  hive_flutter: ^0.2.1
  built_value: ^6.7.1
  http_parser: ^3.1.3
  provider: ^3.1.0
  get_it: ^3.0.1
  mime: ^0.9.6+3
  hive: ^1.1.1
  dio: ^3.0.3

  # UI Utilities
  functional_widget_annotation: ^0.5.1
  flutter_platform_widgets: ^0.20.1

  # UI Widgets
  flare_splash_screen: ^2.1.3
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  built_value_generator: ^6.7.1
  functional_widget: ^0.7.1
  hive_generator: ^0.5.2
  build_runner: ^1.7.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/fonts/
    - assets/images/
    - assets/lang/en.json
    - assets/lang/es.json
    - assets/lang/ru.json

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
