name: provider_start
description: A production ready flutter application template for the provider architecture.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  stacked: ^1.7.6

  # Utilities
  shared_preferences: ^0.5.8
  connectivity: ^0.4.9
  app_settings: ^4.0.2
  device_info: ^0.4.2+4
  path_provider: ^1.6.11
  hive_flutter: ^0.3.1
  built_value: ^7.1.0
  pedantic: ^1.9.0
  logging: ^0.11.4
  get_it: ^4.0.4
  mime: ^0.9.6+3
  hive: ^1.4.2
  get: ^3.4.3
  dio: ^3.0.10

  # UI Utilities
  flutter_platform_widgets: ^0.60.1

  # UI Widgets
  cupertino_icons: ^0.1.3
  flare_flutter: ^2.0.3
  auto_route: ^0.6.7

dependency_overrides:
  dartx: ^0.4.1
  path: 1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.5
  built_value_generator: ^7.1.0
  hive_generator: ^0.7.0+2
  auto_route_generator: ^0.6.7
  build_runner: ^1.10.0
  mockito: ^4.1.1
  logger: ^0.9.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/fonts/
    - assets/images/
    - assets/lang/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
